Fix build
I'm not sure if this is a recent change but person.bio is being returned
as Markdown and so needs to be used to set the inner HTML instead of
passing it as an object into the template which was causing an error
like:

```
WebpackError: Minified React error #31; visit
https://reactjs.org/docs/error-d
  ecoder.html?invariant=31&args[]=object%20with%20keys%20%7BchildMarkdownRemark%
  7D for the full message or use the non-minified dev environment for
  full error  s and additional helpful warnings.
```